- hosts: all
  become: true
  tasks:
    - name: Activer nginx via amazon-linux-extras
      shell: amazon-linux-extras enable nginx1
      args:
        creates: /etc/yum.repos.d/amzn2extra-nginx1.repo

    - name: Mettre à jour la liste des paquets
      yum:
        name: "*"
        state: latest

    - name: Installer nginx
      yum:
        name: nginx
        state: present

    - name: Démarrer nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Déployer un fichier HTML statique
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html

